
version: '3'
services:
  
  geth-bootnode:
    image: ethereum/client-go:alltools-v1.13.15
    command: 'bootnode --addr 172.16.239.10:30301 --nodekey=/pepe/bootnode.key'
    volumes:
      - ./bootnode.key:/pepe/bootnode.key
    networks:
      ethnetwork:
        ipv4_address: 172.16.239.10
  
  
  rpc1:
    image: ethereum/client-go:v1.13.15
    volumes:
      - ./rpc1:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      ethnetwork:
        ipv4_address: 172.16.239.20
    ports:
      - "8546:8545"
    entrypoint: sh -c 'geth init /root/genesis.json && geth --bootnodes="undefined" --nat "extip:172.16.239.20" --netrestrict=undefined --http --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "*" --http.api "admin,eth,debug,miner,net,txpool,personal,web3"'
  

  miner1:
    image: ethereum/client-go:v1.13.15
    volumes:
      - ./miner1:/root/.ethereum
      - ./genesis.json:/root/genesis.json
      - ./password.txt:/root/.ethereum/password.sec
      - ./keystore:/root/.ethereum/keystore
    depends_on:
      - geth-bootnode
    networks:
      ethnetwork:
        ipv4_address: 172.16.239.30
    entrypoint: sh -c 'geth init /root/genesis.json && geth --nat "extip:172.16.239.30" --bootnodes="undefined" --miner.etherbase undefined --mine --unlock undefined --password /root/.ethereum/password.sec'
  

  rpc2:
    image: ethereum/client-go:v1.13.15
    volumes:
      - ./rpc2:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      ethnetwork:
        ipv4_address: 172.16.239.40
    ports:
      - "8547:8545"
    entrypoint: sh -c 'geth init /root/genesis.json && geth --bootnodes="undefined" --nat "extip:172.16.239.40" --netrestrict=undefined --http --http.addr "0.0.0.0" --http.port 8545 --http.corsdomain "*" --http.api "admin,eth,debug,miner,net,txpool,personal,web3"'
  

  normal1:
    image: ethereum/client-go:v1.13.15
    volumes:
      - ./normal1:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    depends_on:
      - geth-bootnode
    networks:
      ethnetwork:
        ipv4_address: 172.16.239.50
    entrypoint: sh -c 'geth init /root/genesis.json && geth --bootnodes="undefined" --nat "extip:172.16.239.50" --netrestrict=undefined'
  
networks:
  ethnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
  